#!/usr/bin/env python3
import pandas as pd
import lib
from sys import argv
import re

df = pd.read_csv(argv[1],sep="\t")

pat = re.compile(r"__[A-Z]+__")
def sub(t):
  return pat.sub("",t)

df["text"] = df["text"].apply(sub)
df = lib.whitespace(df)

df.to_csv(argv[1] + ".bare.tsv", index=False, sep="\t")
