#!/usr/bin/env python3
import pandas as pd
import numpy as np
import seaborn as sns
import sys
import lib as l
import matplotlib.pyplot as plt
from scipy.cluster import hierarchy

cmap = l.cmap()


x = pd.read_csv(sys.argv[1],sep="\t").drop(columns="id")

def reorder(rho):
  row_linkage = hierarchy.linkage(rho.values)
  col_linkage = hierarchy.linkage(rho.values.T)
  
  rows =        hierarchy.leaves_list(row_linkage)
  cols =        hierarchy.leaves_list(row_linkage)
  return rho.iloc[rows,cols]

for method in ["pearson","kendall","spearman"]:
  rho = x.corr(method=method)
  rho = reorder(rho)
  rho.to_csv(sys.argv[2] + "." + method,sep="\t")
  fig = sns.heatmap(rho,vmin=-1,vmax=1,cmap=cmap,annot=True,annot_kws={"size":8}).get_figure()
  fig.tight_layout()
  fig.savefig(sys.argv[3] + "." + method + "." + "png",dpi=200)
  plt.clf()
  plt.cla()
