#!/usr/bin/env python3
import pandas as pd
import sys
import numpy as np
from scipy import stats

df = pd.read_csv(sys.argv[1],delimiter="\t")

fora = df["forum"].unique()


for x in fora:
  print(x)

for x in fora:
  stat = pd.DataFrame()
  sdf = df.loc[df["forum"] == x]
  sdf = sdf.drop(columns=["forum","id"])
  print(len(sdf))
  stat["proxy-measure"] = [c for c in sdf]
  stat["mean"]   =   [np.mean(sdf[c]) for c in sdf]
  stat["mode"]   =   [stats.mode(sdf[c]).mode[0] for c in sdf]
  stat["median"] = [np.median(sdf[c]) for c in sdf]
  stat["std dev"]    =    [np.std( sdf[c]) for c in sdf] 
  
  sdf["forum"] = x
  stat.to_csv(sys.argv[2]+ "." + x,sep="\t")
  
