#!/usr/bin/env python3
import seaborn as sns
import pandas as pd
import sys
import matplotlib.pyplot as plt

df = pd.read_csv(sys.argv[1],delimiter="\t")
df.head()

v=sys.argv[2]
print(df[v])

sns.displot(df[v])

plt.axvline(x=df[v].mean(), color="black")
plt.axvline(x=df[v].median(), color="blue",ls="--")

plt.savefig(sys.argv[3])
