#!/usr/bin/env python3
import seaborn as sns
import pandas as pd
import sys

df = pd.read_csv(sys.argv[1],delimiter="\t")
df.head()

v=sys.argv[2]
print(df[v])

sns.displot(df[v]).fig.savefig(sys.argv[3])
