#!/usr/bin/env python3
import pandas as pd
import lib as l
import sys
import json

if __name__ == "__main__":
  df = l.load(sys.argv[1])
  df["mean-node-types-per-sentence"] = [sum([len(list(set(nodes))) for nodes in x])/float(len(x)) for x in df["node-type-list"].apply(json.loads)]
  l.saveid2x(df,"mean-node-types-per-sentence",sys.argv[2])
