#!/usr/bin/env python3
import pandas as pd
import numpy as np
import sys
import json

def mwl(json_sents):
  sents = json.loads(json_sents)
  word_lengths = [len(w) for s in sents for w in s]
  return np.mean(word_lengths)

def main(id2sentences, outfile):
  n = "mean-word-length"
  id2sentences[n] = id2sentences["sentences"].apply(mwl)
  id2sentences[["id",n]].to_csv(outfile,sep="\t",index=False)

if __name__ == "__main__":
  main(pd.read_csv(sys.argv[1],sep="\t"),sys.argv[2]) 
