#!/usr/bin/env python3
import pandas as pd
import sys
from functools import reduce

if(len(sys.argv) <= 2):
  print("why?")
  exit()
joiners = sys.argv[1:-2]
dest = sys.argv[-1]


def l(s):
  return pd.read_csv(x,delimiter="\t")


joined = reduce(lambda a,x: a.merge(,on="by"),joiners[1:],l(joiners[0]))
