#!/usr/bin/env python3
import pandas as pd
import numpy as np
import seaborn as sns
import sys
import lib as l
import matplotlib.pyplot as plt
from scipy.cluster import hierarchy
from scipy.stats import pearsonr
from scipy.stats import spearmanr

cmap = l.cmap()

x = pd.read_csv(sys.argv[1],sep="\t").drop(columns="id")
x = l.reorder(x)

def reg_coef(x,y,label=None,color=None,**kwargs):
    ax = plt.gca()
    r,p = pearsonr(x,y)
    spearman,pspearman = spearmanr(x,y)
    ax.annotate('Pearson\'s r = {:.2f}\nSpearman\'s r = {:.2f}'.format(r,spearman), xy=(0.5,0.5), xycoords='axes fraction', ha='center')
    ax.set_axis_off()


def hist(x,label=None,color=None,**kwargs):
  return sns.histplot(x,label=label,color=color,kde=True)

g = sns.PairGrid(x)
g.map_diag(hist)
#g.map_diag(sns.kdeplot)
g.map_lower(sns.scatterplot)
g.map_upper(reg_coef)
g.tight_layout()
g.savefig(sys.argv[2],dpi=200)
