#!/usr/bin/env python3
import pandas as pd
import numpy as np
import seaborn as sns
import sys
import lib as l
import matplotlib.pyplot as plt
from scipy.cluster import hierarchy
from scipy.stats import pearsonr

cmap = l.cmap()


x = pd.read_csv(sys.argv[1],sep="\t").drop(columns="id")
x = l.reorder(x)

def reg_coef(x,y,label=None,color=None,**kwargs):
    ax = plt.gca()
    r,p = pearsonr(x,y)
    ax.annotate('r = {:.2f}'.format(r), xy=(0.5,0.5), xycoords='axes fraction', ha='center')
    ax.set_axis_off()

g = sns.PairGrid(x)
g.map_diag(sns.kdeplot)
g.map_lower(sns.regplot)
g.map_upper(reg_coef)
g.tight_layout()
g.savefig(sys.argv[2],dpi=200)
