#!/usr/bin/env python3
import pandas as pd
import lib as l

def main(df,outfile):
  import seaborn as sns
  fig = sns.pairplot(df)
  fig.tight_layout()
  fig.savefig(outfile,dpi=200)

if __name__ == "__main__":
  import sys
  df = pd.read_csv(sys.argv[1],sep="\t").drop(columns="id")
  df = l.reorder(df)
  main(df,sys.argv[2])
