#!/usr/bin/env python3
import pandas as pd
import sys

parses = pd.read_pickle(sys.argv[1])
small = pd.read_csv(sys.argv[2],delimiter="\t")


df = small.merge(parses,on="id")

print(len(df))

df.to_pickle(sys.argv[3])
