#!/usr/bin/env python3
import pandas as pd
import texthero as hero
import numpy as np
from scipy.special import softmax
import sys
import json
from gensim import corpora

df = pd.read_csv(sys.argv[2],delimiter="\t")

dct = corpora.Dictionary(json.loads(d) for d in df[sys.argv[1] + "-json"])


df = pd.DataFrame([(k,dct.cfs[v]) for k,v in dct.token2id.items()],columns=["token","frequency"])

df = df.sort_values("frequency")

df["rank"] = df["frequency"].rank(method="dense",ascending=False) 
df["log-log-rank-order"] = np.maximum(np.log10(np.log10(df["rank"])),0)

df.to_csv(sys.argv[3],sep="\t",index=False)
